import logging

POLLING_ROUTES = frozenset(
    {
        "/api/market",
        "/api/decisions",
        "/api/portfolio",
        "/api/events",
        "/api/accounts",
        "/api/control/status",
    }
)


class PollingAccessLogFilter(logging.Filter):
    """Hide successful access logs generated by the dashboard refresh loop."""

    def filter(self, record: logging.LogRecord) -> bool:
        if (
            record.name != "uvicorn.access"
            or not isinstance(record.args, tuple)
            or len(record.args) != 5
        ):
            return True

        _, method, full_path, _, status_code = record.args
        try:
            status = int(str(status_code))
        except (TypeError, ValueError):
            return True

        path = str(full_path).split("?", 1)[0]
        is_successful_poll = (
            method in {"GET", "OPTIONS"}
            and path in POLLING_ROUTES
            and 200 <= status < 300
        )
        return not is_successful_poll


def configure_logging(level: str) -> None:
    logging.basicConfig(
        level=getattr(logging, level.upper(), logging.INFO),
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )

    access_logger = logging.getLogger("uvicorn.access")
    if not any(isinstance(item, PollingAccessLogFilter) for item in access_logger.filters):
        access_logger.addFilter(PollingAccessLogFilter())
